version: '3'
services:
  backend:
    build: ./server/
    image: tryberankdb
    ports:
      - 5000:5000
  frontend:
    build: ./client
    image: tryberank
    ports:
      - 3000:80
    depends_on:
      - backend