version: '3'
services:
  backend:
    build: ./server/
    image: tryberankdb
    ports:
      - 5000:5000
  frontend:
    build: ./client
    image: tryberank
    volumes:
      - "./client:/app"
    ports:
      - 3000:3000
    depends_on:
      - backend