name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy Front-end
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tryberank"
          heroku_email: "rafaelaugustscherer@gmail.com"
          appdir: client
          usedocker: true
          stack: container
        env:
          HD_REACT_APP_SERVER: 'https://tryberank-api.herokuapp.com'
      - name: Build and Deploy Back-end
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tryberank-api"
          heroku_email: "rafaelaugustscherer@gmail.com"
          appdir: server
          usedocker: true
          stack: container
        env:
          HD_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          HD_ORIGIN: '*'
          HD_SALT: ${{secrets.SALT}}
          HD_TOKEN_KEY: ${{secrets.TOKEN_KEY}}